### ISSUE TITLE
Exit codes

### ISSUE THREAD

**Issue by ChrisMacNaughton** [CanonicalLtd/ceph_safe_disk#2]
It seems to me that the exit code for "Safe to remvoe an OSD" should be 0 in keeping with Unix standards for Ok exits.

``` bash
ubuntu@ip-172-31-61-132:~$ sudo ./ceph-safe-disk -q
● Safe to remove an OSD
ubuntu@ip-172-31-61-132:~$ echo $?
2
```

**Comment by 0X1A** [comment]
Makes sense, before the exit status `0` simply meant exited without error but it's definitely more useful if it shows that a disk is removable.

**Comment by ChrisMacNaughton** [comment]
well, a LOT of programming languages (ex: Python) will actually throw an exception if a sub process exits non-zero :)
