### ISSUE TITLE
Timing

### ISSUE THREAD

**Issue by ChrisMacNaughton** [CanonicalLtd/ceph_safe_disk#3]
How quickly will this detect off drives? I stopped the OSD service on one of 3 nodes and ran it on one of the mons immediately and it showed me Ok to remove any OSD the first time; subsequent runs showed not to remove things but made me curious about timing.

**Comment by 0X1A** [comment]
When ever ceph starts showing that the OSD is down is when we'll be able to see that they're down. I'm not sure of the exact timing but it does take a few seconds.

**Comment by cholcombe973** [comment]
Yeah that's true depending on the timeout values for the osds.

**Comment by 0X1A** [comment]
I made a note of this on the README and linked to the ceph documentation, closing this unless there are any other suggestions
